name = "CMPSKit"
uuid = "e12464de-de28-4143-b5d1-34185b1dff4c"
authors = ["Jutho Haegeman <jutho.haegeman@ugent.be> and contributors"]
version = "0.1.0"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OptimKit = "77e91f04-9b3b-57a6-a776-40b61faaebe0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
KrylovKit = "0.5.2"
OptimKit = "0.1, 0.2"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
